### ISSUE TITLE
Strong name the NuGet build

### ISSUE THREAD

**Issue by BlueToque** [viceroypenguin/RBush#1]
Hi - sorry if this is the wrong venue for this.

I'd like to use this package in an application I am developing. Installed the NuGet package via Visual Studio. 

However, the assembly does not have a strong name. Since the rest of my application is strong named due to security requirements, I cannot load RBush without cloning the repo and compiling it myself.

This isn't a bug, but it is a request to strong name the NuGet package

**Comment by viceroypenguin** [comment]
Thank you for your request. I apologize for taking so long to get back to you. I have updated the package, and it has passed through CI. Nuget has received the package and should update their library shortly. Version 1.0.20 is strong-named per your request.

**Comment by chhh** [comment]
Sorry for necromancy, but that may be not such a great idea: https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/
