### ISSUE TITLE
RBush and rotated rectangles

### ISSUE THREAD

**Issue by charlenni** [viceroypenguin/RBush#43]
Hello,

first, I would say thank you for your work.

Is it possible to change RBush, so that it works with rotated rectangles? Any idea? Perhaps first check for the outer rect and if they overlap to check, if it also overlaps with the inner rotated rect? Where to start?

Any help is appreciated.

**Comment by viceroypenguin** [comment]
Apologies for the late response - I missed the notification in the December busyness of life.

> Is it possible to change RBush, so that it works with rotated rectangles?
Not in a way that is easily compatible with existing implementation/existing users.

> Perhaps first check for the outer rect and if they overlap to check, if it also overlaps with the inner rotated rect? 
Yes, this is the path, but it should be done by the consumer, not by RBush.
