### ISSUE TITLE
Transitive package vulnerabilities. System.Net.Http and System.Text.RegularExpressions.

### ISSUE THREAD

**Issue by chillitom** [viceroypenguin/RBush#53]
NuGet's built in security audit functionality is warning that transitive dependencies `System.Text.RegularExpressions` and `System.Net.Http` have known security vulnerabilities.

```
Warning As Error: Package 'System.Net.Http' 4.3.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-7jgj-8wvc-jh57
Warning As Error: Package 'System.Text.RegularExpressions' 4.3.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-cmhx-cq75-c4mj
```

![image](https://github.com/user-attachments/assets/71083437-c58c-4256-8bde-ceb71b457020)

They seem to come in from the `netstandard1.6` library.

This could be resolved by taking a direct dependency on the libraries at versions 4.3.1 and 4.3.4 respectively or by target a more recent netstandard.  What would the preferred approach be?

Related: https://github.com/ClosedXML/ClosedXML/pull/2500 and https://github.com/ClosedXML/ClosedXML/issues/2491

**Comment by viceroypenguin** [comment]
Addressed with v4.0.0 in 5a8b10352d531a7a445b6e1e3bf1d4a61c56ed03
