### ISSUE TITLE
A Question about Insert

### ISSUE THREAD

**Issue by SneakyTactician** [viceroypenguin/RBush#6]
Does the RBush.Insert() function detect if there is duplicates? If so, what does it do when it finds a duplicate?

Thanks!

**Comment by viceroypenguin** [comment]
No, currently `RBush.Insert()` does not give any consideration to duplicates.

**Comment by SneakyTactician** [comment]
Good to know! I thought that might have been the case, so I began coding assuming that. 

Thanks
