### ISSUE TITLE
tree traversal

### ISSUE THREAD

**Issue by ShadyNawara** [viceroypenguin/RBush#7]
Hi, Is there currently a way to traverse the tree as with the original RBush

**Comment by viceroypenguin** [comment]
Comparison to the original library:
* `.Search()` with no parameters matches the `.all()` function
* `.Search(in Envelope boundingBox)` matches the `.search()` function.

I assume one of these two functions matches what you're looking for.

**Comment by shandoosheri** [comment]
what i am trying to do is a depth first traversal. because search would just simply return a list of all elements in the tree.

**Comment by viceroypenguin** [comment]
RBush does not currently implement a depth-first traversal. If you would like to write one, I can review and possibly include it.

**Comment by DanAvni** [comment]
@shandoosheri, Not sure it will help but have a loot at https://github.com/morelinq/MoreLINQ
They have depth first traversal as part of their extensions to LINQ
