### ISSUE TITLE
performance improvment

### ISSUE THREAD

**Issue by rogomax** [viceroypenguin/RBush#9]
RBush.BuildNodes() replace data.Skip(left).Take(num).ToList() by data.GetRange(left, num) double BulkLoad() performance during my benchmark.

				if (height == 1)
				{
					//return new Node(data.Skip(left).Take(num).ToList(), height);
					return new Node(data.GetRange(left, num), height);
				}

Note that, if you forget to set maxEntries during RBush construction, BulkLoad() will be very, very, very slow. I suggest to verify the capacity of the RTree in the first lines of Bulkload(). Unfortunatly it is a bit more code than just updating min & maxEntries as in the constructor.

**Comment by viceroypenguin** [comment]
Implemented. In the future, this would be a case for a PR rather than an Issue. With a PR, I can review and simply approve; as an Issue, I have to copy your change into my code and push it.
